###
GET http://localhost:7003

###

POST http://localhost:7003/auth/register
Content-Type: application/json

{
  "username": "Akosh12345",
  "password": "222443"
}


###
POST http://localhost:7003/auth/login
Content-Type: application/json

{
  "username": "Avinash",
  "password": "123123"
}
